package com.aquanz.jboot.demo.codegened.model;

import io.jboot.db.annotation.Table;
import com.aquanz.jboot.demo.codegened.modelbase.BaseTNotes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_notes", primaryKey = "id")
public class TNotes extends BaseTNotes<TNotes> {
	
}
