package com.aquanz.jboot.demo.codegened.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTNotes<M extends BaseTNotes<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setCheckSyncTime(java.util.Date checkSyncTime) {
		set("check_sync_time", checkSyncTime);
	}
	
	public java.util.Date getCheckSyncTime() {
		return get("check_sync_time");
	}

}
